name = "invoice-line-item-demo"
compatibility_date = "2025-01-03"
workers_dev = false

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "drop-trailing-slash"

[[routes]]
pattern = "invoice-line-item-demo.marek.work"
custom_domain = true
