name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: cf-worker-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: ğŸ“¥ Install deps
        run: pnpm i --frozen-lockfile

      - name: ğŸ—ï¸ Build demo app
        run: cd apps/demo && pnpm build

      - name: ğŸ—ï¸ Build storybook
        run: cd apps/demo && pnpm build-storybook

      - name: ğŸš€ Deploy demo app to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/demo
          command: deploy --config wrangler-demo.toml

      - name: ğŸš€ Deploy storybook to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/demo
          command: deploy --config wrangler-storybook.toml
